packaging_format = 2

id = "stylo"
name = "Stylo"
description.en = "Text editor for scientific articles in the humanities and social sciences"
description.fr = "Éditeur de textes pour articles scientifiques en sciences humaines et sociales"

version = "3.0.6~ynh1"

maintainers = [ ]

[upstream]
license = "GPL-3.0"
website = "https://stylo.huma-num.fr/"
demo = "https://stylo.huma-num.fr/"
admindoc = "https://github.com/EcrituresNumeriques/stylo/blob/master/HOWTO.md"
userdoc = "https://stylo-doc.ecrituresnumeriques.ca/fr_FR/#!index.md"
code = "https://github.com/EcrituresNumeriques/stylo/"

[integration]
yunohost = ">= 11.1.29"
architectures = "all"
multi_instance = true
ldap = false
sso =  false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/EcrituresNumeriques/stylo/archive/refs/tags/v3.0.6.tar.gz"
        sha256 = "255c7d6152fc33c250c61f57206b0a8d762dea3930cbe7d64b4974f1d2caf0a6"

    [resources.ports]
    main.default = 3000
    graph.default = 3030
    export.default = 3060

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "pandoc"
    